name: flutter_auto_cache

packages:
  - .

scripts:
  clean:
    run: flutter clean && flutter pub get

  test_coverage:
    run: flutter test --test-randomize-ordering-seed=random --coverage

  format:
    run: dart format --set-exit-if-changed --line-length 120 .
