name: auto_cache_manager
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutterando_analysis: ^0.0.2
  mocktail: ^1.0.3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
