name: "Collaboration & Issue Workflow"

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: toshimaru/auto-author-assign@v2.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
