name: "Issues Workflow"

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
