name: Continuous Delivery (CD)

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)"]
    types:
      - completed

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_commit.message, 'v')

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Check Version
        id: check_version
        run: chmod +x ./.github/scripts/verfiy_version_tags.sh && ./.github/scripts/verfiy_version_tags.sh

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: "Flutter Pub Get"
        run: flutter pub get

      - name: "Publish"
        run: "dart pub publish --dry-run"
