name: Continuous Delivery (CD)

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Check Version
        id: check_version
        run: chmod +x ./.github/scripts/verify_versions.sh && ./.github/scripts/verify_versions.sh

      - name: "Flutter Action"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.x
          channel: "stable"

      - name: "Flutter Pub Get"
        run: flutter pub get

      - name: "Publish"
        run: "dart pub publish --dry-run"
