name: Continuos Integration (CI)

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Analyzer & Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test --test-randomize-ordering-seed=random --coverage --machine

      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "/coverage/lcov.info"
          min_coverage: 80
          exclude: "**/*_observer.dart **/change.dart"
