name: "Code Quality"

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    tags:
      - "v*"

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run Dart Analyzer
        run: flutter analyze

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "dart"

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
